### ISSUE TITLE
BUG: Opening a source edit does not use the correct domain.

### ISSUE THREAD

**Issue by rolandschuetz** [code-q-web-factory/CodeQ.LinkChecker#10]
I found a new bug during usage<img width="1712" alt="Bildschirm­foto 2022-12-13 um 15 23 25" src="https://user-images.githubusercontent.com/735982/207358734-7ef13a7a-4c81-460f-bee0-83cb195c08e2.png">
See example above, the edit button loads to https://www.neos.eu/... instead of wien.neos.eu
And in the text, the "https: > > " looks a bit weird.

**Comment by mhsdesign** [comment]
i fear we should invest into https://github.com/code-q-web-factory/CodeQ.LinkChecker/issues/6
