### ISSUE TITLE
Undefined index: FLOW_REWRITEURLS

### ISSUE THREAD

**Issue by simonschaufi** [code-q-web-factory/CodeQ.LinkChecker#17]
Hey,

I've got this notice, when I run `./flow checklinks:crawlnodes`:

Notice: Undefined index: FLOW_REWRITEURLS in /home/.../Data/Temporary/Development/Cache/Code/Flow_Object_Classes/CodeQ_LinkChecker_Command_CheckLinksCommandController.php line 315

I guess it needs to be done like: `$_SERVER['FLOW_REWRITEURLS'] ?? null`

**Comment by rolandschuetz** [comment]
This is already fixed here and will be released soon together with some more fixes:
https://github.com/code-q-web-factory/CodeQ.LinkChecker/commit/5e47618455b8ee6a12e60383c2265e2e50076eeb
